# Find all the papers written by a given author that where published in database conferences.

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sdm: <http://www.bdma.upc/#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?paper WHERE {
   ?author sdm:submit ?paper .
}
