Prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
Prefix owl: <http://www.w3.org/2002/07/owl#>
Prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
#Prefix xsd: <http://www.w3.org/2001/XMLSchema#>
Prefix sdm: <http://www.bdma.upc/#>

select ?s where {
    ?s rdf:type sdm:Author
} limit 50

#select ?Authors where { 
#	?Authors rdf:type sdm:Author .
#} limit 100 
#